name: Push Patch

concurrency:
  group: versioning
  cancel-in-progress: true

on:
  push:
    branches: [patch]

jobs:
  build:
    name: Build and Release Patch
    runs-on: ubuntu-latest
    steps:
      # you would probably build something here
      - name: Do Something
        run: echo blah blah blah

      # get the release to upload to
      - name: Release
        uses: gaseum-labs/uhc-versioning@v1.0.0
        with:
          version_type: patch
          upload_file: demo.txt
          base_version: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
