name: Push Major

concurrency:
  group: versioning
  cancel-in-progress: true

on:
  push:
    branches: [major]

jobs:
  build:
    name: Build and Release Major
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # you would probably build something here
      - name: Do Something
        run: echo blah blah blah

      # get the release to upload to
      - name: Release
        uses: gaseum-labs/uhc-versioning@v1.0.0
        with:
          version_type: major
          upload_file: demo.txt
          base_version: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
